[package]
name = "diesel_demo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
diesel = { version = "2", features = ["postgres"] }
dotenvy = "0.15"

[[bin]]
name = "write_post"
doc = false

[lib]
doc = false